---
title: "sobol_with_ode"
author: "Patty Park, Mariam Garcia, Hazel Vaquero"
output: html_document
---

# Assignment: Using Sobel with an ODE
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
#read libraries
library(tidyverse)
library(deSolve)
library(sensitivity)
```

## Part 1

```{r}
#load in function
source("forestgrwth.R")
```

## Part 2

```{r}
#create parms list
parms <- list(K = 250, r = 0.01, g = 2)

#create yearly time frame
simtimes = seq(from=1, to=300)

#run ode with forestgrwth function
result = ode(y = 10, time=simtimes, func=forestgrwth, parms=parms)

#rename column name to appropriate names
colnames(result)=c("time","C")

result = as.data.frame(result)

#find the time it takes to get the threshold
thresh = 50
idx = which(result$C > thresh)[1]
# if it never gets there
idx = ifelse(is.na(idx), length(result$P), idx)
# turn this index into a year (might be the same if time step in 1 but just in case it isn't)
threshyear = result$time[idx]
threshyear

```

## Part 3

```{r}
growthgraph <- ggplot(data = result,
                      aes(x = time, y = C)) +
  geom_point(col = "cornflowerblue") +
  geom_vline(xintercept=threshyear, col="red") +
  labs(x = "Time",
       y = "Forest Growth",
       title="Where Canopy Closure exceeds 50kgC") +
  theme_bw()

print(growthgraph)
```

## Part 4
```{r}
#set for maximum years
np=300

#set parameters
r = rnorm(mean=0.01, sd=0.001, n=np)
K = rnorm(mean=250, sd=25, n=np)
g = rnorm(mean=2, sd=0.2, n=np)
X1 = cbind.data.frame(r=r, K=K, g=g)

# repeat to get our second set of samples
r = rnorm(mean=0.01, sd=0.001, n=np)
K = rnorm(mean=250, sd=25, n=np)
g = rnorm(mean=2, sd=0.2, n=np)
X2 = cbind.data.frame(r=r, K=K, g=g)

# create our sobol object and get sets of parameters for running the model
sens_forest = sobolSalt(model = NULL, X1, X2, nboot = 300)
colnames(sens_forest$X)= c("r","K", "g")

head(sens_forest$X) #this is the variability of growth rate

#conduct sobol indicies for each metric
sens_P_maxpop = sensitivity::tell(sens_forest, allres$maxpop)
```

### Part 5

